### ISSUE TITLE
Multiple things wrong here

### ISSUE THREAD

**Issue by Betterbird** [flathub/eu.betterbird.Betterbird#1]
1. Weren't [eu.betterbird.Betterbird.appdata.xml](https://github.com/flathub/eu.betterbird.Betterbird/blob/master/eu.betterbird.Betterbird.appdata.xml) and [eu.betterbird.Betterbird.desktop](https://github.com/flathub/eu.betterbird.Betterbird/blob/master/eu.betterbird.Betterbird.desktop) going to be removed (or at least refreshed from https://github.com/Betterbird/thunderbird-patches/tree/main/metadata? The version number is wrong in the XML file.
2. The screenshots are out of date, see https://github.com/Betterbird/thunderbird-patches/tree/main/metadata

**Comment by hfiguiere** [comment]
It failed to build anyway https://buildbot.flathub.org/#/builders/32/builds/106974

**Comment by hfiguiere** [comment]
There is no .desktop file or appdata file in the binary tarball, so no change here.

**Comment by Betterbird** [comment]
Sorry for the ignorance, but allow me some questions:
We have two copies of the appdata XML and desktop files, here and in the Betterbird repo. Is that intentional? So for new releases, the version needs to be changed in two places? Or can one copy be deleted now?

**Comment by hfiguiere** [comment]
> Sorry for the ignorance, but allow me some questions:
> We have two copies of the appdata XML and desktop files, 

That's because you don't ship them in the tarball so they can't be found. Getting them form your repo separatly is a possiblity but I didn't bother I was here to fix the failed build. And just resynched at the same time.

What you should do is SHIP and INSTALL the files in the proper location part of your improvement over Thunderbird so that these repo only contain the manifest.

We do prefer everything (but the manifest managed upstream) just that it is not right now.

**Comment by Betterbird** [comment]
Sorry, all this is beyond me. We spend our time making a better version of TB, so I really don't know how to implement what you're suggesting. I don't even understand what "manifest" refers to. There is a .json and a .xml.

I really don't want to update two .xml's with each release :-(

Can someone please "do the right thing"(TM) and let us know which file to update in the future. @mfschumann kindly created this flatpak, but that can't mean committing us to updating more than one file. For example, the [ARCH packages](https://aur.archlinux.org/packages?O=0&SeB=nd&K=betterbird&outdated=&SB=p&SO=d&PP=50&submit=Go)  are maintained by @Posi81 and that's no additional work for us.

**Comment by hfiguiere** [comment]
Here the expectation is that @mfschumann maitain this here. AUR don't care about the appdata file. Howerver they ship their own .desktop file.

**Comment by mfschumann** [comment]
I have been working on a separate branch trying to build from source. On that branch the issues mentioned above should be fixed. I will merge the fixes here.

**Comment by Betterbird** [comment]
Hmm, the screenshot just got deleted in https://github.com/flathub/eu.betterbird.Betterbird/commit/658f8bedea004125982939dc6225c8e47672a65f.

As for "You maintain the .appdata.xml, meaning that you update the version number on every release." --> In which repo, this one or mine? Looking at "I am already using .desktop and .appdata.xml from upstream", I conclude that you want me to update the version in my (the upstream copy)? I'm fine with that.

**Comment by mfschumann** [comment]
Don't worry about the deleted screenshots - we are taking the ones right from your Betterbird repo, so there is no need to save a copy here.

> As for "You maintain the .appdata.xml, meaning that you update the version number on every release." --> In which repo, this one or mine? 

I meant your repo Betterbird/thunderbird-patches. Thanks a lot for keeping that file up to date.

**Comment by Betterbird** [comment]
I'm not worried about the screenshots. But if they were deleted here and (quote) "on that branch I have updated the screenshots" you will get a conflict. I don't want a copy to return here.

I meant your repo Betterbird/thunderbird-patches. Thanks a lot for keeping that file up to date. --> No problem.

**Comment by hfiguiere** [comment]
> Hmm, the screenshot just got deleted in [658f8be](https://github.com/flathub/eu.betterbird.Betterbird/commit/658f8bedea004125982939dc6225c8e47672a65f).

As my last commit, that actually **fixed the build**, said, I synced the appdata from your version, because this is a change that was easy and worth it, since this was a requested change that didn't get done before the merge. That mean the sceenshot were no longer needed and it's better like that.

Note that missing screenshot is a fatal build error, so it wasn't "just done".
