### ISSUE TITLE
Apply external patches

### ISSUE THREAD

**Issue by mfschumann** [flathub/eu.betterbird.Betterbird#10]
Patches marked with # URL in the series files are not included in the Betterbird repo, but are downloaded directly from Mozilla. Implement this for the flatpak build. 

Complication: during building on flathub, only files listed as sources can be downloaded. So it's probably best to generate a sources list in `update_version.sh` just as for thunderbird-sources.json.

**Comment by Betterbird** [comment]
> Patches marked with # URL in the series files are not included in the Betterbird repo, but are downloaded directly from Mozilla.

Yes, our build script does that with wget. It's simply not to have to store these patches which will come in the upstream repo later anyway. We only store them if we need to rebase them (obviously).
