### ISSUE TITLE
Printing crashes Betterbird 

### ISSUE THREAD

**Issue by mfschumann** [flathub/eu.betterbird.Betterbird#110]
When trying to print, BB crashes:
www.thunderbird-mail.de/forum/thread/92422-betterbird-stürzt-bei-drucken-ab/#post519351

The issue is present in TB Flatpak, but is absent in the non-flatpak version of BB, so the bug is very likely caused by something flatpak-related.

It might help to remove the `--socket=cups` permission:
https://github.com/flathub/org.libreoffice.LibreOffice/issues/90

**Comment by stemabu** [comment]
> It might help to remove the --socket=cups permission
I tried this, but unfortunately it made no difference.

**Comment by stemabu** [comment]
I tried the manually downloaded version of betterbird, and printing did work with it. Otherwise, I also tested flatpak-firefox, where the crash happens. With other flatpak-installations, eg Joplin, or with packet-installations of thunderbird or firefox, I have not problem to open printing dialogue. So it seams to me, that the flatpak print preview of thunderbird/firefox does not work on my installation.

**Comment by mfschumann** [comment]
Do you happen to force using wayland by setting the environment variable `MOZ_ENABLE_WAYLAND`? That seems to have [caused a similar error in the past](https://github.com/flathub/org.mozilla.Thunderbird/issues/134#issuecomment-711506564).

Could you give more examples of flatpaks where printing works for you? Maybe we can find some differences between the packaging of these flatpaks vs. firefox/thunderbird/betterbird. 

Could you also try installing and running the flatpak org.flatpak.qtdemo and see if printing works (click on Portals -> Print...).

**Comment by stemabu** [comment]
Ok, I just tried to set the environment variable in Flatseal, but it made no difference.

Other examples of flatpaks where printing works for me are e.g. Inkscape and Xnview. I also tried org.flatpak.qtdemo and here printing works. Do you have any suggestions which flatpak would be worth testing to find differences vs. firefox/thunderbird?

**Comment by mfschumann** [comment]
I've had a look at the flatpak manifests (the file where the packaging process is defined) and it seems that the ones working for you don't use the `--socket=cups` permission. That means those flatpaks must be using the "print portal" instead for printing. This should work for Firefox as well if I understand the state of [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1688720) correctly. I have confirmed that printing still works when disabling `--socket=cups` on my machine.

So the Firefox/Thunderbird/Betterbird flatpak should already be using the same printing mechanism as the flatpaks that work for you. That this does **not** work for you makes me believe that the problem could be some error that Firefox receives from the print portal and does not handle properly.

@Betterbird Do you know where to look in the Firefox source code for this or do you happen to know any flags that could be used to generate more verbose logging?

**Comment by Betterbird** [comment]
I don't quite unterstand the question. Do you want to debug the printing code in the Mozilla platform? The source code is likely here https://searchfox.org/mozilla-central/source/widget or https://searchfox.org/mozilla-central/source/widget/gtk in files with "print" in their name. A crash stack would be a good starting point.

Looks like there is Gecko logging for printing, with, you guessed it, "printing" as module name:
https://searchfox.org/mozilla-central/rev/7d98e651953f3135d91e98fa6d33efa131aec7ea/layout/base/nsDocumentViewer.cpp#157

So something like this should give you some additional information:
```
export MOZ_LOG=printing:5,timestamp
export MOZ_LOG_FILE=/tmp/log_file
```

No warranty, I didn't try it.

**Comment by mfschumann** [comment]
Thanks, that was what I was looking for. Do you know if there is any documentation on how to enable logging and what modules are available?

@stemabu Could you try to generate a log for the crash?

**Comment by mfschumann** [comment]
There is now a [bug report on the Mozilla bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1851142) too.

**Comment by mfschumann** [comment]
According to the TB bug report the crash was caused by a bug in cups and is supposed to be fixed in the runtime org.freedesktop.Platform version 22.08.15 which should be released very soon.

Closing this issue. Feel free to reopen if the bug still hits you after upgrading org.freedesktop.Platform.

**Comment by stemabu** [comment]
I just realized it. The `flatpak update` was not necessary, update seem to have been automatically. Came exactly at the right time as I need printing this evening. :smiley:

Thank you very much for your support!
