### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by LtSich** [flathub/eu.betterbird.Betterbird#132]
Hi,

I use betterbird with flatpack on Linux.
But since the last update the french translation doesn't work anymore.

When I go to the add-ons sections I have this warning : 
`Français Language Pack is incompatible with Betterbird 115.3.2.`

This is the exact version that I use : 
`115.3.2-bb15 (64-bit)`

I didn't try the linux archive + langage pack atm, as I would like to stay with flatpak.

[EDIT]
The downloadable archive from the website work fine in French.
I will switch on that atm, tbh it could be useful to have the flatpak working fine.
I don't know who manage that one.
[/EDIT]

[EDIT 2]
manually downloading the langage pack, and installing it from files work on the flatpak too.
[/EDIT 2]

**Comment by mfschumann** [comment]
Please remove the language pack that you installed manually and restart the Betterbird flatpak. It should then pick up the language pack that is delivered within the flatpak.
