### ISSUE TITLE
Incorrect WM_CLASS compared to .desktop file, so Plasma's task manager can't match Betterbird to its window

### ISSUE THREAD

**Issue by HugLifeTiZ** [flathub/eu.betterbird.Betterbird#22]
Hi there. The following was mentioned [over here:](https://github.com/Betterbird/thunderbird-patches/issues/75#issuecomment-1242932471)

> I am using the .desktop file setting `StartupWMClass=betterbird-default`, but I see the correct icons nevertheless. The `wmclass` of the running Betterbird (as reported by `lg` -> `Windows`) is `thunderbird-default`, though. So I don't really understand **why** it works for the flatpak.

I'm using this package on Kubuntu 22.04 and taskbar pinning is not working for me out of the box, because the .desktop file's StartupWMClass wants `betterbird-default`, but the actual window's WM_CLASS is `thunderbird-default`. If a StartupWMClass is defined for a .desktop file, that takes precedence over anything else it might use to find an application's windows. So the pinned application on the taskbar is not matched with Betterbird's actual window. I have no idea what GNOME is doing such that it still works for that person.

It's my impression that a recent commit was supposed to change the `WM_CLASS` to `betterbird` or `betterbird-default`? Unfortunately, it did not. It's still `thunderbird-default` on my end, and I definitely have the package built from that commit.

I can work around this issue by making a copy of the .desktop file in `xdg-data/applications` and changing its StartupWMClass to `thunderbird-default`.

**Comment by mfschumann** [comment]
The commit you mentioned did not fix the issue, but it only prepares the flatpak build for the upstream fix scheduled for the next Betterbird release.

That said, I've added a temporary workaround for the flatpak that is available now:
```
flatpak install https://dl.flathub.org/build-repo/107927/eu.betterbird.Betterbird.flatpakref
````

**Comment by HugLifeTiZ** [comment]
It's all good now. Thank you for the quick fix. :)
