### ISSUE TITLE
Clarify BB languages: Chinese and Italian.

### ISSUE THREAD

**Issue by Betterbird** [flathub/eu.betterbird.Betterbird#24]
At a quick glance I saw zh-CN in https://github.com/flathub/eu.betterbird.Betterbird/blob/master/thunderbird-sources.json. What's the story with this file?

We don't ship BB in Chinese since the Chinese localisation of Thunderbird isn't complete. Our Chinese script has placeholders in it:
https://github.com/Betterbird/thunderbird-patches/blob/1770cefd94f1850c74114cedd04a112b74a17026/102/scripts/zh-CN.cmd#L45
(and below). The script hasn't been updated since June 2022, so likely it won't be any good. Please don't ship zh-CN.

We've added Italian to our localisations, I can't see where you record which language packs you build.

If you wish, we can correct our zh-CN.cmd script before applying the 102.3.0-bb17 tag later today. In the current state, it's not usable.

**Comment by mfschumann** [comment]
The thunderbird-sources.json file controls what sources are downloaded (e.g. source archives, language packs). It is auto-generated in https://github.com/flathub/eu.betterbird.Betterbird/blob/1000c5490c047302622c682a9d04f771b3413a96/update-version.sh using
- a tag or commit for your repo given as a command line argument -> determines the commit of your repo we download
- the major version number given as a command line argument (always 102 for now) -> determines which set of Betterbird patches we apply
- the intersection between the list of Thunderbird language packs shipped by Mozilla and the list of Betterbird localization patches provided as  .CMD files in your repo -> determines the localizations we ship

We currently assume that all .CMD files present in thunderbird-patches/102/scripts work. If that is not the case, it would be great if you could fix or rename the non-working ones.

**Comment by Betterbird** [comment]
Something else I saw: Before `zip -qr "../langpack-$lang@betterbird.eu.xpi" manifest.json chrome localization` shouldn't you mimic this:
https://github.com/Betterbird/thunderbird-patches/blob/0d0c09ef9b76d109ebcf8ae84deaa379d1060a5f/102/scripts/langpack.cmd#L26

Otherwise your language packs will contain a chrome/en-US and localization/en-US.
Am I missing something?

Still looking at Chinese, should be ready later today.

**Comment by mfschumann** [comment]
> Something else I saw: Before `zip -qr "../langpack-$lang@betterbird.eu.xpi" manifest.json chrome localization` shouldn't you mimic this: https://github.com/Betterbird/thunderbird-patches/blob/0d0c09ef9b76d109ebcf8ae84deaa379d1060a5f/102/scripts/langpack.cmd#L26
> 
> Otherwise your language packs will contain a chrome/en-US and localization/en-US. Am I missing something?

I only copy brand.ftl, brand.dtd, and brand.properties from the en-US locale to the lang pack that I am modifying: https://github.com/flathub/eu.betterbird.Betterbird/blob/1000c5490c047302622c682a9d04f771b3413a96/apply-patches.sh#L77

So it is not necessary to remove the en-US chrome and localization folders as in your script. This is the result after running `apply-patches.sh 102`:
```
sh-5.1$ ls localization/
de
sh-5.1$ ls chrome/
de
```

Regarding your second comment:
> You're not copying the brand.properties from chrome. It's three files in today.

The command copies brand.dtd and brand.properties from the en-US locale to chrome/$lang/locale/$lang/branding/:
```
sh-5.1$ ls chrome/de/locale/de/branding/
brand.dtd  brand.properties
sh-5.1$ ls localization/de/branding/
brand.ftl
```

Is there anything wrong with how I pack the language pack or with the result?

**Comment by Betterbird** [comment]
OK, sorry, I didn't see the second file being copied, helps to read the entire line 😦. Also, you copy the three files from somewhere, whereas my script unpacks omni.ja and hence has to clean up the unwanted directories later. I had a bug in that 😦 so I thought you have the same problem, but not so.

Summary, your stuff is good, just ignore me.

The Chinese language pack drives me nuts, it's built like the others but I get `Missing resource in locale zh-CN: branding/brand.ftl` although the file is present. Investigation continues.

**Comment by Betterbird** [comment]
https://github.com/Betterbird/thunderbird-patches/commit/1a576ab764561b8201d8faf55efffaed9addb2bf is the best we can do.

Even TB with the zh-CN language pack issues the error `Missing resource in locale zh-CN: branding/brand.ftl` so there's something quite wrong here. The localisation is missing many strings, so it looks quite bad.

**Comment by mfschumann** [comment]
So we are going to include zh-CN ?

**Comment by Betterbird** [comment]
> So we are going to include zh-CN ?

Yes, we might as well. BB 91 shipped in Chinese and there were a few users, one of them even complained about AUR being out of date. See https://github.com/Betterbird/thunderbird-patches/issues/73#issuecomment-1253287958 for details.

We have it at language pack with note "(incomplete)" on our website.
