### ISSUE TITLE
Cannot start message composer when another instance is running

### ISSUE THREAD

**Issue by mfschumann** [flathub/eu.betterbird.Betterbird#33]
I am unable to open a message compose window 
* from the command line using `flatpak run eu.betterbird.Betterbird -compose "to=some@mail.com"` or
* by clicking on a mailto link when Betterbird is set as the mailto handler

when another Betterbird flatpak instance is already running. The following error message is shown:
![image](https://user-images.githubusercontent.com/9102962/192162226-cafaf90c-eb96-4370-8cc8-57c97cfe49cb.png)

Both the binary distributed via betterbird.eu and the Thunderbird flatpak do **not** show this behavior, but instead a compose window is opened in the running instance as expected. So the issue seems to be caused by some error in the building or packaging that is specific to the flatpak version of Betterbird.

I have tried the following without any effect:
- Running the flatpak with an `--own-name` argument (because of [a comment in the flatpak manifest for Thunderbird](https://github.com/flathub/org.mozilla.Thunderbird/blob/4bd98039133e8b70c8cc35c218b254f647ae3061/org.mozilla.Thunderbird.json#L30)). I have tried `eu.betterbird.betterbird_default.*`, `eu.betterbird.betterbird.*`, `eu.betterbird.Betterbird_default.*`, `eu.betterbird.Betterbird.*`, and even `org.mozilla.thunderbird_default.*` (the one used for the Thunderbird flatpak).
- Running under Gnome with X11 vs. Gnome with Wayland.
- When running under Gnome with Wayland: Running Betterbird with native Wayland support vs. without native Wayland support.

@Erick555, @Betterbird: Do you have an idea how detection of the running instance works and what could go wrong in this case? Can you give me any hints on how to debug this issue?

**Comment by Betterbird** [comment]
I'm confused. The comment said that you (unsuccessfully?) tried `eu.betterbird.betterbird_default.*`, yet that is what the pull request "add own-name to make running instance detection work under wayland" adds. Anyway, I won't be of help here, especially given that our binary works.

**Comment by mfschumann** [comment]
The PR #32 was an unsuccessful attempt to fix the issue by adding the `own-name` argument, since this was the only difference I found relevant when comparing the flatpak manifests for Betterbird and Thunderbird. I kept the PR open because like that I can easily get test builds while trying to fix the issue.

**Comment by Erick555** [comment]
Try `flatpak run --log-session-bus eu.betterbird.Betterbird -compose "to=some@mail.com"` and paste the output

**Comment by Betterbird** [comment]
I put my money on this:
https://searchfox.org/comm-central/search?q=org.mozilla.*APP&path=nsDBusRemote&case=false&regexp=true
```
	mozilla/toolkit/components/remote/nsDBusRemoteClient.cpp
142	pathName = nsPrintfCString("/org/mozilla/%s/Remote", appName.get());
153	remoteInterfaceName = nsPrintfCString("org.mozilla.%s", appName.get());
	mozilla/toolkit/components/remote/nsDBusRemoteServer.cpp
66	errorMsg = nsPrintfCString("org.mozilla.%s.Error", mAppName.get());
96	ourInterfaceName = nsPrintfCString("org.mozilla.%s", mAppName.get());
157	nsPrintfCString busName("org.mozilla.%s.%s", mAppName.get(),
170	busName = nsPrintfCString("org.mozilla.%s.%s", mAppName.get(), "default");
189	mPathName = nsPrintfCString("/org/mozilla/%s/Remote", mAppName.get());
```
Maybe not a good idea to patch that since we don't know what else will break if we change it. There are heaps of constructs of this kind:
https://searchfox.org/comm-central/search?q=org.mozilla.*APP&path=&case=false&regexp=true

**Comment by mfschumann** [comment]
> Maybe not a good idea to patch that since we don't know what else will break if we change it. There are heaps of constructs of this kind: https://searchfox.org/comm-central/search?q=org.mozilla.*APP&path=&case=false&regexp=true

Hm, to me these occurrences seem pretty unrelated. But I'm really not an expert on TB/mozilla source code. If you decide against patching I will add the `--own-name='org.mozilla.betterbird.*'` workaround for flatpak packaging, so the issue will be resolved either way. Just let me know your decision and I will either wait for yout patch or add the workaround.

**Comment by Betterbird** [comment]
Let's go with org.mozilla.betterbird.*. This string is not visible to the user. It was a bit different for the WM_CLASS which used to be thunderbird (https://github.com/Betterbird/thunderbird-patches/issues/75). Undeniably Betterbird is based on Mozilla software and we don't want to weed out every little bit of it. Have you noticed that the user agent string is still Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Thunderbird/102.3.0? It's different in the mail header. This is done for a reason: If you browse a feed URL with BB, the client should be treated like TB. We've seen cases where websites react differently based on the UA string and it's possible that Betterbird wouldn't be a recognised browser.

**Comment by Betterbird** [comment]
There is more:
https://searchfox.org/mozilla-central/search?q=org.mozilla.%25&path=&case=false&regexp=false
https://searchfox.org/mozilla-central/rev/ec4996707f5aa721097183d6da6a9546e2fbec30/widget/gtk/DBusService.cpp#39,45-46
https://searchfox.org/mozilla-central/search?q=GetDBusAppName&path=&case=false&regexp=false
https://searchfox.org/mozilla-central/rev/ec4996707f5aa721097183d6da6a9546e2fbec30/xpcom/glue/XREAppData.cpp#50-59
Try setting the app name via MOZ_DBUS_APP_NAME. I think all your issues could be solved by returning "betterbird" hard-coded there.

Note
https://searchfox.org/mozilla-central/search?q=mAppName&path=dbus&case=false&regexp=false
and
https://searchfox.org/mozilla-central/rev/ec4996707f5aa721097183d6da6a9546e2fbec30/toolkit/components/remote/nsDBusRemoteServer.cpp#201

Suggestion:
Try with the the env variable, then change the function:
```C++
void XREAppData::GetDBusAppName(nsACString& aName) const {
  const char* env = getenv("MOZ_DBUS_APP_NAME");
  if (env) {
    aName.Assign(env);
  } else {
    aName.AssignLiteral("betterbird");
  }
}
```

**Comment by Betterbird** [comment]
Try whether this helps:
https://github.com/Betterbird/thunderbird-patches/commit/a8384a61f66d94e51c61024998546d5ab1db2288
(I haven't compiled it.)

**Comment by mfschumann** [comment]
Setting `MOZ_DBUS_APP_NAME=betterbird` fixes the issue. I do that in the flatpak, so no need to change code on your side.

**Comment by Betterbird** [comment]
I've already added the patch, shall I remove it again?

**Comment by mfschumann** [comment]
Makes sense to keep the patch for non-flatpak users running BB with `MOZ_ENABLE_WAYLAND=1`.
