### ISSUE TITLE
How does upstream notify of new versions?

### ISSUE THREAD

**Issue by Betterbird** [flathub/eu.betterbird.Betterbird#6]
Hi @hfiguiere and @mfschumann: New version 102.2.1-bb15, see https://github.com/Betterbird/thunderbird-patches/commit/526010ec03eb942a5f5379d402386a6b6c890b44. How does upstream notify you?

Change [eu.betterbird.Betterbird.appdata.xml](https://github.com/flathub/eu.betterbird.Betterbird/blob/master/eu.betterbird.Betterbird.appdata.xml) for now?

Also please note for issue #2 that if you build from source, you'll have to build against the corresponding tag, in this case 102.2.1-bb15.

**Comment by mfschumann** [comment]
I will look into setting up a GitHub action that watches for new tags or changes to the .appdata.xml in your repo.

**Comment by Betterbird** [comment]
So should we edit the "local" XML file to trigger a new build?

**Comment by mfschumann** [comment]
Actually I think it's best to trigger only on a new tag in your repo. Like that we can use a workflow like this:
1. You update the version in .appdata.xml some time during preparing the next release.
1. Once the release is ready, you push a tag containing the version number of the release, triggering a github action in my repo.
1. The github action updates the flatpak manifest for the new version, commits the changes and creates a pull request.
1. The pull request triggers the flathub build bot to create a test build. 
1. Once I have tested the created flatpak, I complete the pull request, triggering the flathub build bot to create a build that will be published. 

The only piece that's missing to realize this automated workflow is the github action in step 3, so this step is currently manual.

**Comment by Betterbird** [comment]
I'm fine with triggering the flatpak via the application of the tag.

**Comment by mfschumann** [comment]
So I'll close this issue. Implementing the GitHub action is tracked in #9.
