### ISSUE TITLE
BB flatpak uses TB icons

### ISSUE THREAD

**Issue by Betterbird** [flathub/eu.betterbird.Betterbird#7]
Someone sent me this screenshot, I didn't try it myself.
![1VYshgWOqlkBv06O](https://user-images.githubusercontent.com/86832723/187995368-50b2edfe-22f8-457a-9044-4587919d6f42.png)

**Comment by mfschumann** [comment]
Hm, that's strange. Is that screenshot taken with the version 102.2.0-bb14 published on flathub?

**Comment by Betterbird** [comment]
@Posi81 ?

**Comment by Posi81** [comment]
Yes it is with 102.2.0-bb14

**Comment by mfschumann** [comment]
Would you mind giving 102.2.1-bb15 a try and see if the problem persists? That version is on flathub now.

**Comment by vinzv** [comment]
Looks fine with 102.2.1-bb15 from flathub:

![grafik](https://user-images.githubusercontent.com/74432/188425773-05dcd061-4dea-471b-bade-d2f2370579f9.png)

![grafik](https://user-images.githubusercontent.com/74432/188425807-186883b7-b6a5-426d-8199-a846514aa8a4.png)

**Comment by mfschumann** [comment]
Ok, thanks for testing. I'll close this issue then.
