### ISSUE TITLE
Systray icon looks blurry

### ISSUE THREAD

**Issue by mfschumann** [flathub/eu.betterbird.Betterbird#78]
Follow-up to https://github.com/Betterbird/thunderbird-patches/issues/155

Observed on KDE only with the flatpak version of Betterbird.

**Comment by mfschumann** [comment]
I can reproduce the issue on Manjaro KDE, but Fedora with Gnome works fine. I'll see if I can find he root cause.

**Comment by peterlobster** [comment]
![image](https://github.com/flathub/eu.betterbird.Betterbird/assets/38382145/3cb0f9c3-39c4-49d9-8189-cc0f25a1e982)

It's okay on mine, but it has this bounding black box that doesn't make it look great. I'm using Fedora 38. I'm also using Blur My Shell.

**Comment by Zahrun** [comment]
I can reproduce too

**Comment by mfschumann** [comment]
@Lungenpest @Zahrun Mind to give the test build in #136 a try and see if it fixes the blurry icon in KDE?

**Comment by Zahrun** [comment]
I installed the test branch flatpak and the result is the same as in https://github.com/Betterbird/thunderbird-patches/issues/214#issuecomment-1827201485: the systray item has no icon though, it is fully transparent.

**Comment by Zahrun** [comment]
I tried to remove explicitly org.kde.StatusNotifierWatcher, in which case the icon comes, but is still blurry

**Comment by mfschumann** [comment]
I have implemented another fix that made a non-blurry, fully functional icon appear in my Gnome session under Wayland. @Zahrun Could you test if the fix works for you, too? The test build containing the fix is available here: https://github.com/flathub/eu.betterbird.Betterbird/pull/136#issuecomment-1828615842

**Comment by Zahrun** [comment]
I confirm it works
Thank you
