### ISSUE TITLE
Summary shouldn't mirror descripton

### ISSUE THREAD

**Issue by razzeee** [flathub/eu.betterbird.Betterbird#94]
Description shouldn't be the same as summary.

Also the summary sholudn't end with a fullstop.

https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

**Comment by mfschumann** [comment]
@Betterbird Would you mind to update the .appdata.xml accordingly?

**Comment by Betterbird** [comment]
Done. We love full stops, especially if they are terminating complete sentences or are part of our motto. Certainly we can't replace
### Betterbird is a soft fork of Mozilla Thunderbird. Simply better.
with
### Betterbird is a soft fork of Mozilla Thunderbird. Simply better

**Comment by mfschumann** [comment]
Thanks. The fix will be included in the next regular release of the flatpak. Closing this issue.
